# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8362588c2fea4a1d62a4f4002f06ddabd1ca70c30a7545cc863910b1f62369813742eaabe0ee89d25b0c0d872f69f6366bc607facbab59b97ed21c185e812c07

test:
  secret_key_base: 57ead15375a4f783455ca6b8fb003fb1c9866dd535cdc52c1dcf6ea744d3d249272bce7731ffad3cf70a001039c4943a2eadf6e82ac410461a94b8732000890d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
